// icons that are needed go here. This is a fix for:
// https://github.com/ant-design/ant-design/issues/12011
// This icon file is generated by build/generateIcons.ts
// tslint:disable
const emptyIcon = {
    name:  'it does not matter',
    theme: 'fill', //  this matter tho
};
export {emptyIcon};
